schema_version = "1.0.0"
id = "io_scene_mvr"
name = "Scene MVR (.mvr) and GDTF (.gdtf)"
version = "1.3.2"
tagline = "My Virtual Rig and General Device Type Format"
maintainer = "NRG Sille <nrgsille@gmx.de>"
type = "add-on"
tags = ["Import-Export", "Scene", "Lighting", "Tracking", "Rigging"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/nrgsille76/io_scene_mvr"
copyright = ["2024 Sebastian Schrand"]
wheels = [
  "wheels/py_mvr-0.6.0-py3-none-any.whl",
  "wheels/py_gdtf-1.0.4-py3-none-any.whl",
  "wheels/io_scene_3ds-2.7.6-py3-none-any.whl",
]

[permissions]
files = "General Device Type Format and My Virtual Rig files"

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  ".*",
  "*.pyc",
  "__pycache__",
  "*.zip",
  "data.json",
]










